//import  DeckList  from './styles'

export function DeckList() {
  return (
    <DeckList>
      <li>
        <img
          src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
          alt="pokemon1"
        />
        <span>Bulbassouro</span>
      </li>
      <li>
        <img
          src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
          alt="pokemon1"
        />
        <span>Bulbassouro</span>
      </li>
      <li>
        <img
          src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
          alt="pokemon1"
        />
        <span>Bulbassouro</span>
      </li>
      <li>
        <img
          src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
          alt="pokemon1"
        />
        <span>Bulbassouro</span>
      </li>
      <li>
        <img
          src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
          alt="pokemon1"
        />
        <span>Bulbassouro</span>
      </li>
      <li>
        <img
          src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
          alt="pokemon1"
        />
        <span>Bulbassouro</span>
      </li>
      <li>
        <img
          src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
          alt="pokemon1"
        />
        <span>Bulbassouro</span>
      </li>
      <li>
        <img
          src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
          alt="pokemon1"
        />
        <span>Bulbassouro</span>
      </li>
      <li>
        <img
          src="https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png"
          alt="pokemon1"
        />
        <span>Bulbassouro</span>
      </li>
    </DeckList>
  )
}
